server:
  port: 8080

spring:
  application:
    name: unisync
  
  data:
    mongodb:
      uri: mongodb+srv://db_user:Tharaka123@cluster0.fzeodo2.mongodb.net/unisync?retryWrites=true&w=majority&appName=Cluster0

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 461070201433-c3obgh3qd91kjri2u9v6olsqv4ekclb3.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        provider:
          google:
            user-name-attribute: sub

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours
